development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cordel_development
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cordel_test
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cordel_production
  username: root
  password: root
