common: &common
  solr:
    hostname: localhost
    port: 8983

production:
  <<: *common

development:
  <<: *common
  solr:
    port: 8982
    log_level: INFO

test:
  <<: *common
  solr:
    port: 8981